### ISSUE TITLE
Receber relatório de desenvolvimento no fechamentos de milestone

### ISSUE THREAD

**Issue by JaimeJuan11** [fga-eps-mds/MDS-2020-2-G2#98]
## Descrição

Receber um relatório de desenvolvimento em markdown após o fechamento de uma milestone com as métricas de desenvolvimento da equipe utilizando a API do github.

## Objetivos

- [x] Criar um relatório em markdown descrevendo as métricas de desenvolvimento da equipe durante o período em que a milestone esteve aberta;
- [x] Fazer o download do relatório automaticamente após o fechamento da milestone.

## Critérios de Aceitação:

- [x] Conseguir criar um relatório com informações úteis;
- [x] Relatório ser aprovado pelos demais membros da equipe;
- [x] Conseguir fazer o download do relatório automaticamente após fechar a milestone.

**Comment by LorrayneCardozo** [comment]
o relatório de desenvolvimento irá conter os seguintes dados:

![image](https://user-images.githubusercontent.com/78423506/115129065-f0f02180-9fb8-11eb-8bf9-cb500f1d21fe.png)
![image](https://user-images.githubusercontent.com/78423506/115129071-fc434d00-9fb8-11eb-9a5b-01c42a73661b.png)

**Comment by LorrayneCardozo** [comment]
após algumas mudanças, o relatório conterá as seguintes informações:

![image](https://user-images.githubusercontent.com/78423506/115782964-a98bdb80-a392-11eb-8f98-0c8fc8d88e4f.png)
![image](https://user-images.githubusercontent.com/78423506/115782972-ac86cc00-a392-11eb-8686-12686669469d.png)
